DROP TABLE IF EXISTS m2m_Pizza_Order;
DROP TABLE IF EXISTS m2m_Pizzas_Ingredients;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Pizzas;
DROP TABLE IF EXISTS Ingredients;
DROP TABLE IF EXISTS Addresses;
DROP TABLE IF EXISTS Customers;